import "./globals.css";
import Navbar from "@/components/Navbar";
import { Libre_Franklin } from "next/font/google";
import localFont from "next/font/local";
import { ReactNode} from "react";
import Footer from "@/components/Footer"

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  variable: "--font-libreFranklin",
  display: "swap",
});

const a_garamond_pro = localFont({
  src: [
    {
      path: "../public/fonts/AGaramondPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/AGaramondPro-Italic.otf",
      weight: '400',
      style: "italic",
    },
    {
      path: "../public/fonts/AGaramondPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/AGaramondPro-BoldItalic.otf",
      weight: "700",
      style: "italic",
    }
  ],
  variable: "--font-a_garamond_pro",
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${a_garamond_pro.variable} ${libreFranklin.variable}`}>
      <body className="font-body dark-theme min-h-screen">
        <Navbar />
        <div className="max-w-7xl mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
